accounts = [
    {
        "exchange":"Binance",
        "instrument":"Spot",
        "nickname":"BinanSpot",
        "value_currency":"USDT",
        "accessKey":"",
        "secretKey":""
    },
    {
        "exchange":"Binance",
        "instrument":"Futures",
        "nickname":"BinanFutures",
        "value_currency":"USDT",
        "accessKey":"",
        "secretKey":""
    },
    {
        "exchange":"Upbit",
        "instrument":"Spot",
        "nickname":"UpSpot",
        "value_currency":"KRW",
        "accessKey":"",
        "secretKey":""
    }
]